### ISSUE TITLE
Is the script meant to be very slow?

### ISSUE THREAD

**Issue by captchaunited** [nikitastupin/clairvoyance#33]
My first run of it has been going overnight, hasn't produced anything yet.

Console is filled with a bunch of warnings,

```
[WARNING][2022-03-20 12:42:35 oracle.py:303]	Unknown error message: 'Cannot query field "xxxx" on type "Query".'
[DEBUG][2022-03-20 12:42:35 oracle.py:324]	get_typeref('Cannot query field "xxxx" on type "Query".', 'InputValue') -> None
[WARNING][2022-03-20 12:42:37 oracle.py:303]	Unknown error message: 'Cannot query field "xxxx" on type "Query".'
[DEBUG][2022-03-20 12:42:37 oracle.py:324]	get_typeref('Cannot query field "xxxx" on type "Query".', 'InputValue') -> None
[WARNING][2022-03-20 12:42:39 oracle.py:303]	Unknown error message: 'Cannot query field "xxxx" on type "Query".'
[DEBUG][2022-03-20 12:42:39 oracle.py:324]	get_typeref('Cannot query field "xxxx" on type "Query".', 'InputValue') -> None
```

**Comment by nikitastupin** [comment]
Hi @captchaunited! It supposed to run relatively fast. In your case it might be either (1) an edge-case bug related to the GraphQL API you've tested against or (2) too large wordlist.

**Comment by Azathothas** [comment]
Hi @nikitastupin how much time would the script take if the wordlist used is the [google-10000-english](https://github.com/first20hours/google-10000-english) as recommended on the main wiki. 
I have tested the GraphQL endpoint manually and there seems to be no rate limits imposed on the amount of queries, so that could be excluded as the probable cause because the script has been running for over 12hrs now...

**Comment by nikitastupin** [comment]
Hey @Azathothas,

It depends on a particular endpoint. However, 12 hours is definitely more than it should. Perhaps, the endpoint runs on a framework that's not supported by clairvoyance yet or it has some other obstacle.

**Comment by nikitastupin** [comment]
#40 might resolve performance and some other issues

**Comment by nikitastupin** [comment]
Also, you may check out the output file while Clairvoyance is still running because it outputs intermediate schema as it builds it (no need to wait until it ends).
