### ISSUE TITLE
Handling single quotations after multiple_suggestions_re detection

### ISSUE THREAD

**Issue by MdotTIM** [nikitastupin/clairvoyance#34]
line 38 of the `oracle.py` should be changed to
```
valid_fields.add(m.strip('"').strip('\''))
```
since if a response had multiple field suggestions and their names were in single quotes, the field name would be saved as `'field_name'` and not `field_name` .

**Comment by nikitastupin** [comment]
Hey @MdotTIM, thank you for raising this! I've pushed the change at https://github.com/nikitastupin/clairvoyance/commit/968680686fb12c16648d0d23d4a36199c2310599. Feel free to close the issue if the program works for you now 😃
