### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by abl3s1** [nikitastupin/clairvoyance#48]
this happening all the time
Also can't import headers, how do I import them correctly?

**Comment by c3b5aw** [comment]
You did not received correct json documents.
If you had problem with authentication, this must be related.

The error is catchable here https://github.com/nikitastupin/clairvoyance/blob/main/clairvoyance/client.py#L59, however this forward an error at the runtime.

I assume you are running the program in CLI, you will import headers like curl does.

```
clairvoyance -o schema.json -H "Authorization: Bearer Token" -H "AnotherHeader: Placeholder" http://example.com
```

**Comment by pythonicable** [comment]
yes. I imported the correct headers, and it throws me the same error after a bit.

**Comment by d-kar** [comment]
Have the same problem. The issue is that server starts blocking requests with 403 error at some point. Probably just too many at the same time (default is 50 threads). Might try to reduce threads to 1 with '-c' option.
clairvoyance only handles 500+ errors to retry, might want to handle 403 errors more gracefully.

**Comment by Privat33r-dev** [comment]
> yes. I imported the correct headers, and it throws me the same error after a bit.

Sorry for extremely late response. The error was caused by rate limiting on the server-side. Currently all the similar issues are covered by #107. 

If you feel that this is the Clarivoyance's issue, then feel free to open a new issue or write here.
