### ISSUE TITLE
Infinite Loop When TypeRef References Parent TypeRef

### ISSUE THREAD

**Issue by seanmarpo** [nikitastupin/clairvoyance#49]
Clairvoyance cannot handle when a schema typeref back-references a typeref. The tool ends up stuck in an infinite loop and never progresses. 

The tool gets caught in `get_path_from_root()` in `graphql.py` where there is a while loop that never completes. I ended up monkey-patching the `oracle.py` to avoid specific TypeName's that have this back reference.

Attached is a screenshot of a schema which does this. I had to kill the tool and the resulting schema showed the issue when thrown into a visualizer.
<img width="893" alt="Screen Shot 2022-08-17 at 11 24 53 PM" src="https://user-images.githubusercontent.com/2565153/185309061-9db3fa49-6622-409c-8421-ada4b25f5b20.png">

**Comment by nikitastupin** [comment]
Hey @seanmarpo,

Thank you for reporting the issue and the detailed report! We'll try to solve this systematically once we have time.

Also, feel free to submit a pull request if you have the solution in mind 😃
