### ISSUE TITLE
JSON Requests are not formulating correctly

### ISSUE THREAD

**Issue by OctaviusRexx** [nikitastupin/clairvoyance#59]
Most JSON Requests are not formulating correctly when sent. I tried to overcome this using a regex inserting closing brackets and a quote for the incorrect JSON but ultimately it is not consistent and the fix cause errors in other queries. You can see this by sending the tool through a web proxy tool (an added cli option for a proxy would be nice too EDIT: just saw this in a pull request). The tool also errors out very quickly getting rid of all data discovered.

**Comment by nikitastupin** [comment]
Hey @OctaviusRexx! Could you check this with the latest (2.5.1) version of Clairvoyance and see whether it solved the problem? Thanks!

**Comment by Privat33r-dev** [comment]
Thank you for this report. Issue is closed due to inactivity as a part of a bigger effort to clean backlog. If you think that issue persists, then feel free to write here or open a new issue.
